$(window).ready ->
  revapi = jQuery('.tp-banner').revolution(
    delay: 15000
    startwidth: 1164
    startheight: 517
    hideThumbs: 10
    fullWidth: 'off'
    fullScreen: 'off'
    fullScreenOffsetContainer: '')

  $('.polyglot-language-switcher').polyglotLanguageSwitcher()
  $('.main-menu__item').hover(-> 
    if $(this).find('.main-menu__dropdown').length > 0 then
    $(this).find('main-menu__dropdown').show()
    )
# ---
# generated by js2coffee 2.0.1
