
$(window).ready ->
  revapi = jQuery('.tp-banner').revolution(
    delay: 15000
    startwidth: 1164
    startheight: 517
    hideThumbs: 10
    fullWidth: 'off'
    fullScreen: 'off'
    fullScreenOffsetContainer: '')
  return
  $('.polyglot-language-switcher').polyglotLanguageSwitcher()

# ---
# generated by js2coffee 2.0.1
